# Generated by Django 4.2.7 on 2024-10-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alunos_professores'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunos',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='professores',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='professores',
            name='matricula',
            field=models.CharField(max_length=5),
        ),
    ]
